import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import styles from './layout.module.css'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: {
    default: '変換ツールズ',
    template: '%s | 変換ツールズ',
  },
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className={styles.wrapper}>
          <div className={styles['header-nav']}>
            <header className={styles['header']}>
              <div className={styles['header-sitetitle']}><a className={styles['header-sitetitle-a']} href="/">変換ツールズ <span style={{fontSize:'10px'}}>by 塩の惑星</span></a></div>
              <div>
                様々な変換をWeb上で行えるようにするサイトです。<br/>
                入力データをサーバに送信しないで処理するので安心して使うことができます。<br/>
              </div>
              <div><a href="/info">サイト詳細</a></div>
              <div><a href="/contact">問合せ</a></div>
            </header>
            <nav className={styles.nav}>
            </nav>
          </div>

          <div className={styles['main-parent']}>
            <main className={styles.main}>
              {children}
            </main>
          </div>
          <footer className={styles.footer}>
          <div className={styles['header-sitetitle']}><a className={styles['header-sitetitle-a']} href="/">変換ツールズ <span style={{fontSize:'10px'}}>by 塩の惑星</span></a></div>
          </footer>
        </div>
      </body>
    </html>
  )
}
